Create database DB_LEBITS
use DB_LEBITS

-- ==========================
-- Criando Tabelas
-- ==========================

-- Tabela: T_LBS_PERSONALIZACAO_LIVRO
CREATE TABLE T_LBS_PERSONALIZACAO_LIVRO (
    cd_personalizacao INT NOT NULL,
    cd_usuario INT NOT NULL,
    nm_fonte VARCHAR(50) NOT NULL,
    vl_luminosidade INT NOT NULL,
    nr_texto_hexadecimal CHAR(6) NOT NULL,
    vl_tamanho INT NOT NULL,
    nr_fundo_hexadecimal CHAR(6) NOT NULL,
    tp_contorno BIT NOT NULL,
    nr_hexadecimal_contorno CHAR(6) NOT NULL,
    tp_modo CHAR(1) NOT NULL
);


-- Tabela: T_LBS_USUARIO
CREATE TABLE T_LBS_USUARIO (
    cd_usuario INT NOT NULL,
    cd_planos INT NOT NULL,
    cd_nivel INT NOT NULL,
    nr_pontos_atuais INT NOT NULL,
    nm_usuario VARCHAR(20) NOT NULL,
    ds_email VARCHAR(100) NOT NULL
);

-- Tabela: T_LBS_PLANOS
CREATE TABLE T_LBS_PLANOS (
    cd_planos INT NOT NULL,
    nm_plano VARCHAR(50) NOT NULL,
    ds_plano VARCHAR(120) NOT NULL
);

-- Tabela: T_LBS_NIVEL
CREATE TABLE T_LBS_NIVEL (
    cd_nivel INT NOT NULL,
    nr_pontos_max INT NOT NULL
);


-- Tabela: T_LBS_ATIVIDADE
CREATE TABLE T_LBS_ATIVIDADE (
    cd_atividade INT NOT NULL,
    nm_atividade VARCHAR(50) NOT NULL,
    ds_atividade VARCHAR(120) NOT NULL,
    nr_pontos INT NOT NULL
); 


-- Tabela: T_NIVEL_ATIVIDADE
CREATE TABLE T_NIVEL_ATIVIDADE (
    cd_nivel INT NOT NULL,
    cd_atividade INT NOT NULL
);


-- Tabela: T_LBS_LIVRO
CREATE TABLE T_LBS_LIVRO (
    cd_livro INT NOT NULL,
    cd_distribuidor INT NOT NULL,
    nm_livro VARCHAR(100) NOT NULL,
    nm_editora VARCHAR(100) NOT NULL,
    nm_autor VARCHAR(50) NOT NULL,
    ds_livro TEXT NOT NULL,
    dt_lancamento DATE,
    vr_nota DECIMAL(2,1) NOT NULL,
    tp_livro CHAR(1) NOT NULL,
    rp_livro VARCHAR(MAX) NOT NULL
);


-- Tabela: T_LBS_DISTRIBUIDOR
CREATE TABLE T_LBS_DISTRIBUIDOR (
    cd_distribuidor INT NOT NULL,
    nm_distribuidor VARCHAR(100) NOT NULL,
    cd_cnpj VARCHAR(14) 
);


-- Tabela: T_LBS_ESTILOS
CREATE TABLE T_LBS_ESTILOS (
    cd_estilo INT NOT NULL,
    nm_estilo VARCHAR(50) NOT NULL
);


-- Tabela: T_ESTILOS_LIVRO
CREATE TABLE T_ESTILOS_LIVRO (
    cd_estilo INT NOT NULL,
    cd_livro INT NOT NULL
);


-- Tabela: T_BIBLIOTECA
CREATE TABLE T_BIBLIOTECA (
    cd_livro INT NOT NULL,
    cd_usuario INT NOT NULL,
    vr_tempo_lido TIME NOT NULL,
    st_livro CHAR(1) NOT NULL,
    tp_favorito BIT NOT NULL,
    dt_adicao DATETIME NOT NULL
);



-- ==========================
-- Criando restrições
-- ==========================


-- Restrições da tabela: T_LBS_PLANOS
ALTER TABLE T_LBS_PLANOS
ADD CONSTRAINT PK_PLANOS PRIMARY KEY (cd_planos);

ALTER TABLE T_LBS_PLANOS
ADD CONSTRAINT UN_PLANOS_NOME UNIQUE (nm_plano);


-- Restrições da tabela: T_LBS_NIVEL
ALTER TABLE T_LBS_NIVEL
ADD CONSTRAINT PK_NIVEL PRIMARY KEY (cd_nivel);

ALTER TABLE T_LBS_NIVEL
ADD CONSTRAINT CK_NIVEL_PONTOS CHECK (nr_pontos_max >= 0);


-- Restrições da tabela: T_LBS_USUARIO
ALTER TABLE T_LBS_USUARIO
ADD CONSTRAINT PK_USUARIO PRIMARY KEY (cd_usuario);

ALTER TABLE T_LBS_USUARIO
ADD CONSTRAINT FK_USUARIO_PLANOS FOREIGN KEY (cd_planos)
    REFERENCES T_LBS_PLANOS (cd_planos);

ALTER TABLE T_LBS_USUARIO
ADD CONSTRAINT FK_USUARIO_NIVEL FOREIGN KEY (cd_nivel)
    REFERENCES T_LBS_NIVEL (cd_nivel);

ALTER TABLE T_LBS_USUARIO
ADD CONSTRAINT UN_USUARIO_EMAIL UNIQUE (ds_email);

ALTER TABLE T_LBS_USUARIO
ADD CONSTRAINT UN_USUARIO_NOME UNIQUE (nm_usuario);

ALTER TABLE T_LBS_USUARIO
ADD CONSTRAINT CK_USUARIO_PONTOS_ATUAIS CHECK (nr_pontos_atuais >= 0);


-- Restrições da tabela: T_LBS_PERSONALIZACAO_LIVRO
ALTER TABLE T_LBS_PERSONALIZACAO_LIVRO
ADD CONSTRAINT PK_PERSONALIZACAO PRIMARY KEY (cd_personalizacao);

ALTER TABLE T_LBS_PERSONALIZACAO_LIVRO
ADD CONSTRAINT FK_PERSONALIZACAO_USUARIO FOREIGN KEY (cd_usuario)
    REFERENCES T_LBS_USUARIO (cd_usuario);

ALTER TABLE T_LBS_PERSONALIZACAO_LIVRO
ADD CONSTRAINT CK_PERSONALIZACAO_LUMINOSIDADE CHECK (vl_luminosidade BETWEEN 0 AND 100);

ALTER TABLE T_LBS_PERSONALIZACAO_LIVRO
ADD CONSTRAINT DF_PERSONALIZACAO_LUMINOSIDADE DEFAULT 80 FOR vl_luminosidade

ALTER TABLE T_LBS_PERSONALIZACAO_LIVRO
ADD CONSTRAINT CK_PERSONALIZACAO_TAMANHO CHECK (vl_tamanho BETWEEN 0 AND 96);

ALTER TABLE T_LBS_PERSONALIZACAO_LIVRO
ADD CONSTRAINT DF_PERSONALIZACAO_TAMANHO DEFAULT 18 FOR vl_tamanho

ALTER TABLE T_LBS_PERSONALIZACAO_LIVRO
ADD CONSTRAINT DF_PERSONALIZACAO_CONTORNO DEFAULT 0 FOR tp_contorno

ALTER TABLE T_LBS_PERSONALIZACAO_LIVRO
ADD CONSTRAINT DF_PERSONALIZACAO_COR_FUNDO DEFAULT '000000' FOR nr_fundo_hexadecimal

ALTER TABLE T_LBS_PERSONALIZACAO_LIVRO
ADD CONSTRAINT CK_PERSONALIZACAO_MODO CHECK (tp_modo IN ('C', 'E', 'P'));  -- C: claro, E: escuro, P: Padrão do dispositivo

ALTER TABLE T_LBS_PERSONALIZACAO_LIVRO
ADD CONSTRAINT DF_PERSONALIZACAO_MODO DEFAULT 'P' FOR tp_modo

ALTER TABLE T_LBS_PERSONALIZACAO_LIVRO
ADD CONSTRAINT DF_PERSONALIZACAO_FONTE DEFAULT 'Arial' FOR nm_fonte

ALTER TABLE T_LBS_PERSONALIZACAO_LIVRO
ADD CONSTRAINT DF_PERSONALIZACAO_COR_TEXTO DEFAULT '000000' FOR nr_texto_hexadecimal


-- Restrições da tabela: T_LBS_ATIVIDADE
ALTER TABLE T_LBS_ATIVIDADE
ADD CONSTRAINT PK_ATIVIDADE PRIMARY KEY (cd_atividade);

ALTER TABLE T_LBS_ATIVIDADE
ADD CONSTRAINT CK_ATIVIDADE_PONTOS CHECK (nr_pontos >= 0);


-- Restrições da tabela: T_NIVEL_ATIVIDADE
ALTER TABLE T_NIVEL_ATIVIDADE
ADD CONSTRAINT PK_NIVEL_ATIVIDADE PRIMARY KEY (cd_nivel, cd_atividade);

ALTER TABLE T_NIVEL_ATIVIDADE
ADD CONSTRAINT FK_NIVEL_ATIVIDADE_NIVEL FOREIGN KEY (cd_nivel)
    REFERENCES T_LBS_NIVEL (cd_nivel);

ALTER TABLE T_NIVEL_ATIVIDADE
ADD CONSTRAINT FK_NIVEL_ATIVIDADE_ATIVIDADE FOREIGN KEY (cd_atividade)
    REFERENCES T_LBS_ATIVIDADE (cd_atividade);



-- Restrições da tabela: T_LBS_DISTRIBUIDOR
ALTER TABLE T_LBS_DISTRIBUIDOR
ADD CONSTRAINT PK_DISTRIBUIDOR PRIMARY KEY (cd_distribuidor);

ALTER TABLE T_LBS_DISTRIBUIDOR
ADD CONSTRAINT UN_DISTRIBUIDOR_CNPJ UNIQUE (cd_cnpj);

ALTER TABLE T_LBS_DISTRIBUIDOR
ADD CONSTRAINT UN_DISTRIBUIDOR_NOME UNIQUE (nm_distribuidor);



-- Restrições da tabela: T_LBS_LIVRO
ALTER TABLE T_LBS_LIVRO
ADD CONSTRAINT PK_LIVRO PRIMARY KEY (cd_livro);

ALTER TABLE T_LBS_LIVRO
ADD CONSTRAINT FK_LIVRO_DISTRIBUIDOR FOREIGN KEY (cd_distribuidor)
    REFERENCES T_LBS_DISTRIBUIDOR (cd_distribuidor);

ALTER TABLE T_LBS_LIVRO
ADD CONSTRAINT CK_LIVRO_NOTA CHECK (vr_nota BETWEEN 0 AND 5);

ALTER TABLE T_LBS_LIVRO
ADD CONSTRAINT CK_LIVRO_TIPO CHECK (tp_livro IN ('C', 'D', 'A'));  -- Comum, Didático e Audiobook

ALTER TABLE T_LBS_LIVRO
ADD CONSTRAINT CK_LIVRO_LANCAMENTO CHECK (dt_lancamento <= GETDATE());



-- Restrições da tabela: T_LBS_ESTILOS
ALTER TABLE T_LBS_ESTILOS
ADD CONSTRAINT PK_ESTILO PRIMARY KEY (cd_estilo);

ALTER TABLE T_LBS_ESTILOS
ADD CONSTRAINT UN_ESTILO_NOME UNIQUE (nm_estilo);


-- Restrições da tabela: T_ESTILOS_LIVRO
ALTER TABLE T_ESTILOS_LIVRO
ADD CONSTRAINT PK_ESTILO_LIVRO PRIMARY KEY (cd_estilo, cd_livro);

ALTER TABLE T_ESTILOS_LIVRO
ADD CONSTRAINT FK_ESTILO_LIVRO_ESTILO FOREIGN KEY (cd_estilo)
    REFERENCES T_LBS_ESTILOS (cd_estilo);

ALTER TABLE T_ESTILOS_LIVRO
ADD CONSTRAINT FK_ESTILO_LIVRO_LIVRO FOREIGN KEY (cd_livro)
    REFERENCES T_LBS_LIVRO (cd_livro);


-- Restrições da tabela: T_BIBLIOTECA
ALTER TABLE T_BIBLIOTECA
ADD CONSTRAINT PK_BIBLIOTECA PRIMARY KEY (cd_livro, cd_usuario);

ALTER TABLE T_BIBLIOTECA
ADD CONSTRAINT FK_BIBLIOTECA_LIVRO FOREIGN KEY (cd_livro)
    REFERENCES T_LBS_LIVRO (cd_livro);

ALTER TABLE T_BIBLIOTECA
ADD CONSTRAINT FK_BIBLIOTECA_USUARIO FOREIGN KEY (cd_usuario)
    REFERENCES T_LBS_USUARIO (cd_usuario);

ALTER TABLE T_BIBLIOTECA
ADD CONSTRAINT CK_BIBLIOTECA_STATUS CHECK (st_livro IN ('L', 'F', 'A')); -- L: Lendo, F: Finalizado, A: Em andamento

ALTER TABLE T_BIBLIOTECA
ADD CONSTRAINT DF_BIBLIOTECA_FAVORITO DEFAULT 0 FOR tp_favorito

ALTER TABLE T_BIBLIOTECA
ADD CONSTRAINT DF_BIBLIOTECA_TEMPO DEFAULT '00:00:00' FOR vr_tempo_lido

ALTER TABLE T_BIBLIOTECA
ADD CONSTRAINT DF_BIBLIOTECA_ADICAO DEFAULT GETDATE() FOR dt_adicao